In [1]:
import numpy as np

In [2]:
array1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[25, 26, 27, 28]])
array2 = np.array([[9,10,11,12]])

# print(array1.shape)
# print(array1.shape)
# print(array2.shape)
print(array1*array2)
# print(np.dot(array1,array2))


[[  9  20  33  48]
 [ 45  60  77  96]
 [225 260 297 336]]
