In [1]:
import numpy as np

In [7]:
def checkDiagonalDominant(m):
    m = np.array(m)
    diag = np.diag(m)
    rowSum = np.sum(np.abs(m), axis=1)
    sumWithoutDiag = rowSum - np.abs(diag)
    print(diag)
    return np.all(np.abs(diag) > sumWithoutDiag)

In [15]:
mX = [
        [
            [10, 2, -6],
            [-1, 4, 2],
            [2, 3, 6]
        ],
        [
            [-5, 2, -8],
            [4, -3, -9],
            [-8, -10, 9]
        ],
        [
            [10, -5, 3, 0],
            [3, -9, 2, -2],
            [-8, 0, 17, -4],
            [3, -3, -8, -15]
        ],
]

mY = [
    [17, -4, -12],
    [13, -7, -2],
    [9, 10, -10, -18]
]



[10  4  6]
True
[-5 -3  9]
False
[ 10  -9  17 -15]
True
